### ISSUE TITLE
Error STEP 10 spectopo

### ISSUE THREAD

**Issue by iwe90** [ChildDevLab/MADE-EEG-preprocessing-pipeline#15]
Hi,
I'm running the MADE pipeline for the first time, using Matlab R2020b and EEGLAB v2021.0. I get the following error in STEP 10:

Error using spectopo (line 297)
Spectopo: non-integer number of epochs

Error in MARA_extract_time_freq_features (line 42)
    [pxx,freq,speccomp,contrib,specstd] = spectopo(icacomps(ic,:), fs, fs);

Error in adjusted_ADJUST (line 347)
cwb=MARA_extract_time_freq_features(EEG);                             %%%

Any ideas why this might be would be appreciated!

Best,
Ivonne

**Comment by ChildDevLab** [comment]
Hi Ivonne,

We need a bit more information in order to figure out what's causing your error:

- What's the size of your EEG.data, EEG.icaact, EEG.icasphere, and EEG.event variables after ICA (step 9) but before you run step 10?
- What type of data are you using? Is it pretty clean overall (ie. adult, sleeping infant, low impedances), or is the data quality not great (ie. awake infant, child, high impedances)?
- How many channels are left in your data after ICA (step 9) but before you run step 10 (aka what is EEG.nbchan)?

Best,
Lydia

**Comment by iwe90** [comment]
Hi, thanks for taking this on! 

Here's some more detail: The data was collected using a 27 electrode cap (plus a separate monopolar EOG channel, which was removed before running the pipeline; since MADE re-references to Cz, the electrode is removed and 26 electrodes remain), 512 Hz sampling rate.

size EEG.data: 26x217014
size EEG.icaact: 26x217014
size EEG.icasphere: 26x26
EEG.event variables after ICA: 1x481

The size of EEG_copy at the beginning of Step 10 is different, since the data is cut into 1s segments:
size EEG_copy.data: 26x512x423
size EEG_copy.icaact: 26x512x423
size EEG_copy.icasphere: 26x26
EEG_copy.event variables after ICA: 1x1327

The data is from awake, 8-10-month-old infants, so not amazing, but okay to work with.

The number of channels after ICA is 26, i.e. no channels were rejected in their entirety before ICA.

Best,
Ivonne

**Comment by ChildDevLab** [comment]
Hi Ivonne,

We would actually not recommend running the full MADE pipeline on EEG data with fewer than 32 channels because it is designed for high-density EEG. Good alternatives would be to use mini-MADE (which can be found on this same github) and performs a very basic preprocessing of EEG data without performing ICA or alternatively the [HAPPILLEE](https://www.biorxiv.org/content/10.1101/2021.07.02.450940v1.abstract) pipeline which is also designed for low-density data.

That aside, we aren't sure based on the information you've given us so far what is causing your error. If you still intend to use MADE, you can email me at lyoder@umd.edu with both the script you are using as well as the data file that is causing the error and I'll take a look.

Best,
Lydia
