### ISSUE TITLE
Error in Adjusted_ADJUST

### ISSUE THREAD

**Issue by manonkrol** [ChildDevLab/MADE-EEG-preprocessing-pipeline#16]
When running the Adjusted_ADJUST function I get the following error:
Unrecognized function or variable 'compute_GD_feat'.

Error in adjusted_ADJUST (line 219)
GDSF = compute_GD_feat(topografie,EEG.chanlocs(1,pos_channels),size(EEG.icawinv,2));

It is also not able to recognize the functions that come after this line. 
What could be the issue? Thank you for your help.

**Comment by ChildDevLab** [comment]
Hello, 

It looks like you are missing the ADJUST plugin from your MATLAB path. The plugins you need to install in order to run the MADE pipeline are as follows:

% MFFMatlabIO: https://github.com/arnodelorme/mffmatlabio/blob/master/README.txt
% FASTER: https://sourceforge.net/projects/faster/
% ADJUST: https://www.nitrc.org/projects/adjust/

Best,
Lydia

**Comment by manonkrol** [comment]
Dear Lydia,

Thank you for your help. It seems to work fine now.

Best wishes,
Manon
