### ISSUE TITLE
4 Errors after running section "Loop over all data files" (Line 193)

### ISSUE THREAD

**Issue by cbpickro13** [ChildDevLab/MADE-EEG-preprocessing-pipeline#2]
Hello, 
I have hit another error with the pipeline (I have not made any changes to the script). 
Matlab v R2020a, 

Here are the errors, which I'm assuming is a cascade effect based off the first error: 
Error using findpeaks
Too many output arguments.

Error in MARA_extract_time_freq_features (line 80)
    [pks, locs, widths, proms] = findpeaks(resids_pxx(4:16),[4:16]); %looks for
    peaks btw 5 and 15 Hz (1 less and more so any bumps at 5 or 15 are caught)

Error in adjusted_ADJUST (line 347)
cwb=MARA_extract_time_freq_features(EEG);                             %%%

Error in MADE_pipeline_v1_0_Test (line 555)
        badICs = adjusted_ADJUST(EEG_copy, [[output_location filesep 'ica_data'
        filesep] strrep(datafile_names{subject}, ext, '_adjust_report')]);

Looking into the first error online community suggested running >> which findpeaks. I ran this and received the following: \\ad.umn.edu\cehd\Home\cpickron\Documents\eeglab2019_1\plugins\PrepPipeline0.55.3\utilities\chronux_2_modified\spectral_analysis\continuous\findpeaks.m

I understand that the pipeline is made to be user friendly so I'm not sure the best way to trouble shoot these issues - if it is up to me to figure out the matlab code issue or if seeking help is appropriate. 
Many thanks! 
-Charisse

**Comment by StephLeach** [comment]
Hello Charisse ( @cbpickro13 ),

Our apologies for the late reply. We encourage users to post any issues they are having to the github page so that we can help resolve these issues to the best of our ability. 

Based on the information you provided, it seems that you are pulling in a different version of findpeaks.m than what the MADE pipeline expects. The MADE pipeline uses the findpeaks function from the signal processing toolbox (the Matlab add-on). Because you appear to be using a findpeaks.m version located in an eeglab toolbox plugin, the fastest way to resolve this issue would be to run the following line of code before running MADE.

`rmpath('\ad.umn.edu\cehd\Home\cpickron\Documents\eeglab2019_1\plugins\PrepPipeline0.55.3')`

This will remove the PrepPipeline0.55.3 folder from your matlab path. Once this path has been removed, the MADE pipeline should find and use the findpeaks.m function in the signal processing toolbox. 

Please let us know if you have any questions or if the line of code above does not resolve the issue.

-Steph

**Comment by cbpickro13** [comment]
Thanks Steph! 
I tried running the code but kept hitting a warning saying that the path didn't exist. Instead I manually removed the PrepPipeLine and all of the related paths and that seemed to allow the script to run further. I've hit another Error, which I've posted to the pop_rmbase related thread #5 I wasn't sure if I should start a new thread or tack on to the one already started bc it is related to pop_rmbase, but not the same error. 
Thanks!
