### ISSUE TITLE
Error: Error in adjusted_ADJUST (line 154)

### ISSUE THREAD

**Issue by trollerrenfr** [ChildDevLab/MADE-EEG-preprocessing-pipeline#3]
Hi MADE Team!

Thanks for making such a great open-access tool for EEG analysis.  I am running MADE on my first dataset and I ran into an error.

Some info from my setup:
Operating System: Windows 10 (virtual machine)
Matlab Version: 2019a
EEGLab Version: 2019_1
MADE: Downloaded from Github in September 2020

Information about the error:
Screenshot:
![pasted image 0](https://user-images.githubusercontent.com/41809246/96355032-5e270680-10ab-11eb-865c-e2508db1ae9b.png)

This error does not happen with every file.  Happy to provide a sample file if you would like.

Thanks for your help!
Sonya

**Comment by StephLeach** [comment]
Hi Sonya,

Thank you for the detailed information on the error and your setup. 

This error usually occurs when the rank of the data matrix is less than the number of channels. Adjusted-ADJUST and ADJUST do not work when the rank of the data matrix is less than the number of channels. There are a few things that can cause this (e.g., flat channels or channels that are perfectly correlated with each other). In order to prevent this issue, we have added code to the ICA prep section that removes flat channels. Additionally, we have added a conditional statement that only runs ADJUST or Adjusted-ADJUST if the rank of the data matrix is equal to the number of channels. In cases where this condition is not met, the user will have to manually remove bad independent components. This fix will be available with V1_1 of the pipeline. 

```
% Find flat channels
 flatChans = find(range(squeeze(EEG_copy.data(ch,:,:)),1) < 1);
 if ~isempty(flatChans)
     artifacted_epochs(flatChans) = 1;
 end
```


```
    if size(EEG_copy.icaweights,1) == size(EEG_copy.icaweights,2)
        if output_format == 3 % if BIDS format
            cd([output_location_derivatives filesep current_subject]) % move to this folder so that bump jpeg saves in derivatives folder
            badICs = adjusted_ADJUST(EEG_copy, [output_location_derivatives filesep current_subject '_adjust_report']); % save in raw data folder
        else % if not BIDS format
            if save_interim_result==1
                badICs = adjusted_ADJUST(EEG_copy, [[output_location filesep 'ica_data' filesep] strrep(datafile_names{subject}, ext, '_adjust_report')]);
            else
                badICs = adjusted_ADJUST(EEG_copy, [[output_location filesep 'processed_data' filesep] strrep(datafile_names{subject}, ext, '_adjust_report')]);
            end
        end
        close all;
    else % if rank is less than the number of electrodes, throw a warning message
        warning('The rank is less than the number of electrodes. ADJUST will be skipped. Artefacted ICs will have to be manually rejected for this participant');
    end
```


If this does not solve your issue, please contact sleach12@umd.edu and she can look over a sample file to try and determine the root cause of the error.
