### ISSUE TITLE
ERROR: Index exceeds the number of array elements (7) - Line 60 and Line 219

### ISSUE THREAD

**Issue by trollerrenfr** [ChildDevLab/MADE-EEG-preprocessing-pipeline#4]
Hi MADE Team!

Thanks for making such a great open-access tool for EEG analysis.  I am running MADE on my first dataset and I ran into an error.

Some info from my setup:
Operating System: Windows 10 (virtual machine)
Matlab Version: 2019a
EEGLab Version: 2019_1
MADE: Downloaded from Github in September 2020

Information about the error:
Screenshot:
![Screen Shot 2020-10-17 at 7 05 56 PM](https://user-images.githubusercontent.com/41809246/96355093-e3122000-10ab-11eb-8f26-b97ee53782dd.png)

This error does not happen with every file.  Happy to provide a sample file if you would like.

Thanks for your help!
Sonya

**Comment by StephLeach** [comment]
Hi Sonya,

Thank you for the detailed information on the error and your setup. 

This error is common when a dataset has had too many channels removed by FASTER or the ICA preparation steps. Adjusted-ADJUST and ADJUST require at least 11 channels to run properly. In order to prevent crashes like these in the future, we have added code to the ICA prep portion that saves the dataset as having no usable data if greater than 20% of the channels have been removed. This fix will be available with V1_1 of the pipeline. 

```
        % If > 20%, but not all of the channels are bad, save the dataset at this stage and ignore the remaining of the preprocessing.
        elseif numel(ica_prep_badChans) > 0.2*EEG.nbchan
            all_bad_channels=1;
            warning(['No usable data for datafile', datafile_names{subject}]);
            if output_format==1
                EEG = eeg_checkset(EEG);
                EEG = pop_editset(EEG, 'setname',  strrep(datafile_names{subject}, ext, '_no_usable_data_too_many_bad_channels'));
                EEG = pop_saveset(EEG, 'filename', strrep(datafile_names{subject}, ext, '_no_usable_data_too_many_bad_channels.set'),'filepath', [output_location filesep 'processed_data' filesep ]); % save .set format
            elseif output_format==2
                save([[output_location filesep 'processed_data' filesep ] strrep(datafile_names{subject}, ext, '_no_usable_data_too_many_bad_channels.mat')], 'EEG'); % save .mat format
            elseif output_format==3
                EEG = eeg_checkset(EEG);
                EEG = pop_editset(EEG, 'setname',  [current_subject, '_task-', task_name, '_run-01_eeg', '_no_usable_data_too_many_bad_channels']);
                EEG = pop_saveset(EEG, 'filename', [current_subject, '_task-', task_name, '_run-01_eeg', '_no_usable_data_too_many_bad_channels.set'],'filepath', [output_location_derivatives filesep 'eegpreprocess' filesep current_subject]); % save BIDS format
            end
```

If this does not solve your issue, please contact sleach12@umd.edu and she can look over a sample file to try and determine the root cause of the error.
