### ISSUE TITLE
ERROR: Error in pop_rmbase - Step 13 remove baseline

### ISSUE THREAD

**Issue by trollerrenfr** [ChildDevLab/MADE-EEG-preprocessing-pipeline#5]
Hi MADE Team!

Thanks for making such a great open-access tool for EEG analysis.  I am running MADE on my first dataset and I ran into an error.

Some info from my setup:
Operating System: Windows 10 (virtual machine)
Matlab Version: 2019a
EEGLab Version: 2019_1
MADE: Downloaded from Github in September 2020

Information about the error:
Screenshot:

![Screen Shot 2020-10-17 at 7 09 54 PM](https://user-images.githubusercontent.com/41809246/96355138-5d42a480-10ac-11eb-8d48-5b98c63ff2e8.png)

This error happens with every file.  Happy to provide a sample file if you would like.

Thanks for your help!
Sonya

**Comment by StephLeach** [comment]
Hi Sonya,

Thank you for the detailed information on the error and your setup.

It looks like more recent eeglab versions have a modified pop_rmbase() function. To ensure that all eeglab versions after 2013 work with the pipeline, we modified the call for this function. Now, if a user enters [] (to use the entire epoch window), the pipeline will grab the start and stop times for the epoch and use them as the argument for the function.

```
%% STEP 13: Remove baseline
    if remove_baseline==1
        if isempty(baseline_window) % set up for entire epoch
            baseline_window = [EEG.times(1) EEG.times(end)]; % set start and stop times for the baseline window
        end
        EEG = eeg_checkset( EEG );
        EEG = pop_rmbase( EEG, baseline_window);
    end
```

If this does not solve your issue, please contact sleach12@umd.edu and she can look over a sample file to try and determine the root cause of the error.

**Comment by cbpickro13** [comment]
Hi MADE Team,
Using:  
Windows 10
eeglab2019_1

I have hit another pop_rmbase error
![image](https://user-images.githubusercontent.com/64278759/98724421-592b3f00-2359-11eb-93ef-2e0c2515af80.png)

Thanks!
Charisse

**Comment by StephLeach** [comment]
Hi Charisse ( @cbpickro13 ),

Could you let me know what your baseline_window variable is? 

Thanks,
Steph

**Comment by cbpickro13** [comment]
Hi Steph, 
Is this what you are looking for?
baseline_window = [-200  0]; % baseline period in milliseconds (MS) [] = entire epoch

I actually wasn't sure if this is correct. I want to baseline correct 200 ms prior to stim. However, I only want to do this for specific event types. Does it make sense to not baseline correct at this point?

**Comment by StephLeach** [comment]
Hi Charisse,

Yes, that is what I was looking for. Thank you! I wanted to verify that you were not using the entire epoch window before making some initial suggestions. This error suggests that (at least part of) your baseline window is outside of your task_epoch_length window. There are two variables I would recommend checking first.
1) task_epoch_length 
2) task_eeg

If the variable task_epoch_length doesn't start at or before -0.2 seconds (e.g. task_epoch_length =[-0.2 1.0]), this error will happen. Alternatively, if task_epoch_length is valid, but task_eeg=0, you will get this error because you will be using the wrong variable to epoch your data (the script will use rest_epoch_length to create an epoch window of [0 rest_epoch_length]).

If both of these variables are correct (e.g., task_epoch_length is at least [-0.2 1] and task_eeg=1), then I'd need to see what values EEG.times(1) and EEG.times(end) return before I could make any other suggestions.

However, if you don't want to baseline correct all of your epochs, you should skip baseline correction at this point because this function will perform baseline corrections for all epochs.

-Steph

**Comment by cbpickro13** [comment]
Thanks Steph. 
Ok I'll go back and check what the variable values are, as you describe this I remember feeling a bit unsure of what exactly I was supposed to put in for epoch_length.  If these values are set correctly I'll change them and hopefully able to keep moving through the pipeline. 

Basically, what I'll eventually need to do is "create" different categories based on specific events in my file (e.g., fLeft, mLeft are individual events I'd want to create a category that is Left which includes fLeft & mLeft events). So I guess something I'll need to consider is if all epochs should be baseline corrected first OR to baseline correct once the new event categories are created or I guess could just baseline correct a second time through.

**Comment by cbpickro13** [comment]
Hi Steph, 
The epoch length fix worked. Do you have a sense about how long it takes to run the loop section? I know it depends on amount of data. But I'm running the loop section, and it keeps running over and over again on 1 participant and I'm not sure if it will end on it's own? or if I've set it incorrectly. 
![image](https://user-images.githubusercontent.com/64278759/98981270-59efdc80-24e3-11eb-9e2c-4d25fe0491e5.png)
