### ISSUE TITLE
Re-referencing problem

### ISSUE THREAD

**Issue by silvanasp** [ChildDevLab/MADE-EEG-preprocessing-pipeline#7]
We are unfortunately experiencing some problems with the re-referencing. Since this step is at the end of the code (after ICA channel rejection), the resulting EEG struct contains the information from the non-rejected channels only, and it does not include the reference channel (in our case channel 65). 

Do you have any suggestions on how to solve this problem? Could we eventually take the re-referencing step at the very beginning, since we are not using average re-referencing?

Thank you very much in advance!
Silvana

**Comment by StephLeach** [comment]
Hello Silvana Silva Pereira ( @silvanasp ),

Thank you for bringing this to our attention. We typically do re-referencing after all other preprocessing steps because if the new reference channel(s) has/have noise it can spread to other channels. However, if you do re-referencing at the beginning, the subsequent preprocessing steps should remove this noise (since you are not doing an average rereference). 

As you know, unless you chose to interpolate globally rejected channels, we do not have the code set up to add the reference channel back in. If you are interpolating globally rejected channels, you can insert the chunk of code below immediately before re-referencing to return your reference channel to its original state (all zeros) instead of its interpolated state.  

```
reference_channel_index = 65; % please manually change this value if row 65 of your interpolated data matrix does not correspond to your reference channel
EEG.data(reference_channel_index,:,:) = 0; % returns the reference channel to all zeros
```

The code above is based on a 65-channel EGI system. The mff files were imported using mff_import() on a PC with Matlab version 2014b and eeglab13_6_5b. If the code above does not work for you, it may be because the aforementioned systems and/or matlab/toolbox versions differ on your end. 

Please let us know if you have any more questions.

Thanks,
Steph

**Comment by silvanasp** [comment]
Dear Steph, 

Thank you very much for your answer!
In the original pipeline, the data from the reference channel is removed at Step 7.  Therefore, I added the lines you suggested before Step 16 (kept at the end of the for loop), adapted to the new size of the EEG.data matrix:

    _num_chans = size(EEG.data,1);
    reference_channel_index = num_chans+1;
    EEG.data(reference_channel_index,:,:) = 0; % returns the reference channel to all zeros
    
    %% STEP 16: Rereference data
    if rerefer_data==1
        if iscell(reref)==1
%             reref_idx=zeros(1, length(reref));
%             for rr=1:length(reref)
%                 reref_idx(rr)=find(strcmp({EEG.chanlocs.labels}, reref{rr}));
%             end
            reref_idx = reference_channel_index;
            EEG = eeg_checkset(EEG);
            EEG = pop_reref( EEG, reref_idx);
        else
            EEG = eeg_checkset(EEG);
            EEG = pop_reref(EEG, reref);
        end
    end_

However, I get the following warnings:

_eeg_checkset warning: number of columns in data (50) does not match the number of channels (49): corrected
eeg_checkset warning: number of channels different in data and channel file/struct: channel file/struct removed
Warning: the size of the channel location structure does not match with
         number of channels. Channel information has been removed.
Re-referencing data
Error: some channels not used for ICA decomposition are used for rereferencing
       the ICA decomposition has been removed_

It seems that the ICA information was removed. I do not know how  the data is affected. 

--------------------------------------
I take the opportunity to ask about another thing: when data is loaded, one of the messages is:

_Coordinate Layout Name: Geodesic Sensor Net 64 2.0_

Therefore, we choose this layout. However, at line 215 (pop_chanedit) we get the following warning:

_Channel structure size not consistent with the data so changes will be ignored
Use the function pop_select(EEG, 'nochannel', [x]); if you wish the remove data channels_

This warning disappears when loading Geodesic Sensor Net 65 2.0. I do not know what is happening here.

--------------------------------------

Thank you again!
Silvana

**Comment by StephLeach** [comment]
Hi Silvana,

The cause of the last error you mentioned is somewhat related to the eeg_checkset warnings you are getting after adding the reference channel back into the data matrix. So, I’ll answer those two issues together.

For the pop_chanedit() issue, if you check EEG.nbchan after importing your data, you will likely find that it is 65 rather than 64. This means that the reference channel is included in your data matrix (as a row of all zeros) and chanlocs structure (because the chanlocs structure must have information on all of the channels that are a part of data matrix). We’ve noticed that an older version of the mff import function that we use removes the reference channel from the data structure when importing the mff files (making it 64 channels) while the more recent version keeps the reference channel from the data structure when importing the mff files (making it 65 channels). If this is the case for you (aka if EEG.nbchan is 65 instead of 64), then loading the Geodesic Sensor Net 65 2.0 is the right choice. If you try to load the 64 channel version when EEG.nbchan is 65, the EEG.chanlocs structure will not be modified. 
As for the eeg_checkset warnings, you are getting those because you added a row (channel) to the data matrix but not the EEG.chanlocs structure. If you want to keep re-referencing at the end of the script, you’ll have to also add code that will add the reference channel back into the chanlocs structure as well as a line of code changing EEG.nbchan to match the new number of channels. We have not tested code that will add this back in without interpolating all the missing channels back into the data. As such, if you want to re-reference to one or a few electrodes, we recommend putting the re-reference towards the top of the script (after step 2 where you load the channel information).

Finally, the error you are getting about the ICA decomposition is related to the change in the number of electrodes. When you change the number of electrodes, the ICA variables (e.g., EEG.icaact, EEG.icaweights, etc.) can no longer be used to remove artifacts from your data. This does not undo the ICA cleaning done in steps 10 and 11. It only deletes the output variables from the ICA decomposition because they can’t be used anymore. You get this warning after re-referencing because re-referencing will remove the new reference channel(s) from your data matrix.

Please let me know if you run into any more issues or have any more questions.

Thanks,
Steph
