### ISSUE TITLE
Issue running adjusted_ADJUST

### ISSUE THREAD

**Issue by vpKumaravel** [ChildDevLab/MADE-EEG-preprocessing-pipeline#9]
Hi,

I encounter an issue in running ADJUST only for a couple of subjects out of 9. As far as I've understood, it is because of _size(EEG.icaweights,1) being lower than EEG.nbchan_.

The error message is 

**"Click on each trace for channel/component index
Index in position 1 exceeds array bounds (must not exceed 116).

Error in MARA_extract_time_freq_features (line 174)
    plot(nobumps,1:50,resids_pxx_matrix(good_ics(gg),:))

Error in adjusted_ADJUST (line 347)
cwb=MARA_extract_time_freq_features(EEG);                             %%%

Error in singlesubject (line 311)
        badICs = adjusted_ADJUST(EEG_copy, 's13.txt');"**

The steps I followed are as follows:

1) Import the BPF data (we used our own filter settings suited for our requirements)
2) Run FASTER 
3) Prepare data for ICA
4) Run ICA
5) Run adjusted_ADJUST (where the error occurs).

Please suggest. Thanks,

Velu

**Comment by StephLeach** [comment]
Hi Velu,

If the number of ICs is less than the number of electrodes, ADJUST and Adjusted-ADJUST can't be run on the data (see https://github.com/ChildDevLab/MADE-EEG-preprocessing-pipeline/issues/3 for more details on this issue). If this is caused by a flat channel, you can fix the issue by removing the flat channel before running ICA. If two or more perfectly correlated electrodes are causing this, you could solve it by removing some or all of the perfectly correlated electrodes before running ICA. If we have misunderstood your issue and/or failed to answer your question, please reach out again to let us know that the problem has still not been solved.

We've also now modified the older version of MADE to include this warning. 

Thanks,
Steph

**Comment by vpKumaravel** [comment]
Dear Steph, 

Thanks for your feedback, I already anticipated the suggestions.
To fix the issue, I ran both the flat lines method and the correlation method from the [clean_rawdata](https://github.com/sccn/clean_rawdata) plugin on those subjects. An additional number of channels get removed, as a result. 

But, running ICA and adjusted-ADJUST seems smooth. 

Perhaps should you consider including those methods along with FASTER in the pipeline? :-)

Best,
Velu

(p.s. this issue shall be marked as close)
